水素分子に対応するハミルトニアンの対角化

In [26]:
import numpy as np

tp=-0.3
ts=-0.4
Es=-1.5
Ep=-1.2
Eh=-1.0
alpha=np.deg2rad(54)

alpha

0.9424777960769379

In [27]:
H=np.zeros((6,6))
H[0,0]=Es
H[1,1]=Ep 
H[2,2]=Ep 
H[3,3]=Ep
H[4,4]=Eh 
H[5,5]=Eh 

H[0,4]=ts
H[0,5]=ts
H[4,0]=ts
H[5,0]=ts 

H[1,4]=tp*np.cos(alpha)
H[1,5]=tp*np.cos(alpha)
H[2,4]=tp*np.sin(alpha)
H[2,5]=-tp*np.sin(alpha)

H[4,1]=tp*np.cos(alpha)
H[5,1]=tp*np.cos(alpha)
H[4,2]=tp*np.sin(alpha)
H[5,2]=-tp*np.sin(alpha)


In [28]:
H

array([[-1.5       ,  0.        ,  0.        ,  0.        , -0.4       ,
        -0.4       ],
       [ 0.        , -1.2       ,  0.        ,  0.        , -0.17633558,
        -0.17633558],
       [ 0.        ,  0.        , -1.2       ,  0.        , -0.2427051 ,
         0.2427051 ],
       [ 0.        ,  0.        ,  0.        , -1.2       ,  0.        ,
         0.        ],
       [-0.4       , -0.17633558, -0.2427051 ,  0.        , -1.        ,
         0.        ],
       [-0.4       , -0.17633558,  0.2427051 ,  0.        ,  0.        ,
        -1.        ]])

In [29]:
eig,vec=np.linalg.eigh(H)

In [30]:
eig

array([-1.89645224, -1.45750738, -1.24196028, -1.2       , -0.74249262,
       -0.56158748])

In [32]:
vec.T[0,:]

array([8.02147856e-01, 2.01295429e-01, 5.55111512e-17, 1.23259516e-32,
       3.97516645e-01, 3.97516645e-01])

In [33]:
vec.T[1,:]

array([ 2.09013992e-16, -6.65111982e-16, -7.99910777e-01, -6.66133815e-16,
       -4.24348176e-01,  4.24348176e-01])

In [34]:
vec.T[2,:]

array([-3.41841884e-01,  9.26730359e-01, -3.33066907e-16, -3.10613981e-30,
        1.10260980e-01,  1.10260980e-01])